### ISSUE TITLE
Levels & Permissions Issue

### ISSUE THREAD

**Issue by SeoRoman** [z1haze/laravel-acl#4]
Why do permissions have multiple levels if it's tiered?

for instance... why would permissions be assigned to both level 2 and level 4?

if it was assigned Level 4, then Level 2 would automatically have access to it via the heirarchy?

**Comment by z1haze** [comment]
converted the many-to-many relationship to a one-to-many relationship, and updated any code that references it. changes take place in v.0.3.0
